### ISSUE TITLE
Concerns regarding whether libdave is trustworthy

### ISSUE THREAD

**Issue by liz3** [discord/libdave#2]
Hey,
first of all i think the idea of being transparent about the end to end implementation of discord is good and theres a lot of depth to this.

I just see one flaw: theres no way anyone external can verify that the native clients end up using this implementation. How can i be sure this is **not** a reference implementation published and the internal version contains unrelased code altering behaviour?

I again want to stress how important being transparent about the implementation is(which is done), but it is inherently untrustable as long as the rest of the client is not open source either.
While people can reverse engineer the client which gets released to *try* to verify the legitimacy but that is not how it should be done. For users to trust the implementation of DAVE for video and audio calls e2e the entire client needs to be available for external verification.

**Comment by birarda** [comment]
Hi @liz3!

First of all, thank you for the feedback. Discord does not plan to open-source full official clients.

We believe it would be difficult even with an open-source client to prove beyond a shadow of a doubt that the application you download from our website or the App Store uses the exact same open-source code (and nothing else). Our goal in releasing libdave and detailing the protocol is so that you can audit the protocol (using our code or your own) and confirm that our clients are behaving as we've described. With regards to additional undescribed protocol-impacting behaviour in our clients, we expect that security researchers would catch many of these actions and would rightfully publish their alarming findings.

I think it's also worth noting that Trail of Bits completed an audit of our implementation with access not only to libdave but to our full monorepo which includes the code that produces all of our clients.

We will investigate if there are mechanisms we can use to increase trust that Discord clients are in fact using the exact same libdave you see on this repository.
